# Generated by Django 4.0.5 on 2023-10-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationDB',
            fields=[
                ('ID', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyEnrollmentDB',
            fields=[
                ('FacultyID', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Joined', models.DateField(blank=True, null=True)),
                ('Contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Contact', models.CharField(blank=True, max_length=20, null=True)),
                ('AltContact', models.CharField(blank=True, max_length=20, null=True)),
                ('DoB', models.DateField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Joined', models.DateField(blank=True, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Bank', models.CharField(blank=True, max_length=200, null=True)),
                ('Acc_Number', models.IntegerField(blank=True, null=True)),
                ('IFSC', models.CharField(blank=True, max_length=20, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Faculty')),
                ('IsAdmin', models.BooleanField(default=False)),
                ('DeptID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminUI.departmentdb')),
                ('FacultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyUI.facultyenrollmentdb')),
            ],
        ),
    ]
