# Generated by Django 4.0.5 on 2023-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyenrollmentdb',
            name='Department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyenrollmentdb',
            name='Designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
