# Generated by Django 4.0.5 on 2023-10-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0001_initial'),
        ('FacultyUI', '0002_facultyenrollmentdb_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignationDB',
        ),
        migrations.RemoveField(
            model_name='facultydb',
            name='IsAdmin',
        ),
        migrations.AddField(
            model_name='facultyenrollmentdb',
            name='DeptID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminUI.departmentdb'),
        ),
        migrations.AddField(
            model_name='facultyenrollmentdb',
            name='IsAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
