# Generated by Django 4.0.5 on 2023-10-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUI', '0003_delete_designationdb_remove_facultydb_isadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultydb',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='facultydb',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='facultydb',
            name='DeptID',
        ),
        migrations.RemoveField(
            model_name='facultydb',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='facultydb',
            name='Joined',
        ),
        migrations.RemoveField(
            model_name='facultydb',
            name='Name',
        ),
    ]
