# Generated by Django 4.0.5 on 2023-10-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0003_facultyenrollmentdb'),
        ('FacultyUI', '0005_remove_facultydb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydb',
            name='FacultyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.facultyenrollmentdb'),
        ),
        migrations.DeleteModel(
            name='FacultyEnrollmentDB',
        ),
    ]
