# Generated by Django 4.2 on 2023-10-16 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDB',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=20)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentDB',
            fields=[
                ('DeptId', models.AutoField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('StudentId', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=1)),
                ('Email', models.EmailField(max_length=200)),
                ('ContactNo', models.IntegerField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('GuardianName', models.CharField(max_length=200)),
                ('GuardianContact', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='StudentsImage')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentDB',
            fields=[
                ('EnrollmentID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('EnrollDate', models.DateField()),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.coursedb')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.studentdb')),
            ],
        ),
        migrations.AddField(
            model_name='coursedb',
            name='DeptId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.departmentdb'),
        ),
    ]
