# Generated by Django 4.0.5 on 2023-10-18 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='CourseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.coursedb'),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='EnrollDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='EnrollmentID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='FirstName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='GuardianName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='LastName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='EnrollmentDB',
        ),
    ]
