# Generated by Django 4.0.5 on 2023-10-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0002_studentdb_courseid_studentdb_enrolldate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyEnrollmentDB',
            fields=[
                ('FacultyID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Joined', models.DateField(blank=True, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.CharField(blank=True, max_length=20, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('DeptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.departmentdb')),
            ],
        ),
    ]
