# Generated by Django 4.0.5 on 2023-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0003_facultyenrollmentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='StudentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
