# Generated by Django 4.0.5 on 2023-10-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0004_alter_studentdb_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsDB',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Company', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
