# Generated by Django 4.0.5 on 2023-10-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0005_jobsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
