# Generated by Django 4.0.5 on 2023-10-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0007_jobapplicatons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplicatons',
            new_name='JobApplications',
        ),
    ]
