# Generated by Django 4.2.7 on 2023-11-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0008_rename_jobapplicatons_jobapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdb',
            name='image_job',
            field=models.ImageField(blank=True, null=True, upload_to='job'),
        ),
    ]
