# Generated by Django 4.2.7 on 2023-11-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0010_jnewsdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JnewsDB',
            new_name='newsDB',
        ),
    ]
