# Generated by Django 4.2.7 on 2023-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0011_rename_jnewsdb_newsdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='placed_studdb',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=50, null=True)),
                ('p_company', models.CharField(blank=True, max_length=50, null=True)),
                ('p_des', models.CharField(blank=True, max_length=50, null=True)),
                ('p_dis', models.CharField(blank=True, max_length=50, null=True)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='placement')),
            ],
        ),
    ]
