# Generated by Django 4.2.7 on 2023-12-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0013_studentdb_pancard_studentdb_adhaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
