# Generated by Django 4.2.7 on 2024-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0014_studentdb_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'First interview'), ('2', 'Second interview'), ('3', 'Offer letter'), ('4', 'Rejected')], max_length=1)),
            ],
        ),
    ]
