# Generated by Django 4.2.7 on 2024-02-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0015_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdb',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminUI.jobstatus'),
        ),
    ]
