# Generated by Django 5.0.2 on 2024-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0017_marquee'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsDB2',
            fields=[
                ('newsId', models.AutoField(primary_key=True, serialize=False)),
                ('news_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('news_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('news_date', models.DateField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='job')),
            ],
        ),
    ]
