# Generated by Django 5.0.2 on 2024-02-27 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0018_newsdb2'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_text', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.jobsdb')),
            ],
        ),
    ]
