# Generated by Django 5.0.2 on 2024-02-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0019_interviewstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsdb',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.jobsdb'),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='status_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.studentdb'),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
