# Generated by Django 5.0.2 on 2024-02-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0020_remove_jobsdb_status_remove_jobstatus_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobStatus',
            new_name='JobStatus2',
        ),
    ]
