# Generated by Django 5.0.2 on 2024-02-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0021_rename_jobstatus_jobstatus2'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdb',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.studentdb'),
        ),
    ]
