# Generated by Django 5.0.2 on 2024-02-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0022_jobsdb_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsdb',
            old_name='student',
            new_name='StudentId',
        ),
    ]
