# Generated by Django 5.0.2 on 2024-02-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0023_rename_student_jobsdb_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstatus2',
            old_name='student',
            new_name='StudentId',
        ),
    ]
