# Generated by Django 5.0.2 on 2024-02-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0024_rename_student_jobstatus2_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstatus2',
            old_name='StudentId',
            new_name='Student',
        ),
    ]
