# Generated by Django 5.0.2 on 2024-02-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0025_rename_studentid_jobstatus2_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus2',
            name='StudentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.studentdb'),
        ),
        migrations.AlterField(
            model_name='jobstatus2',
            name='Student',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
