# Generated by Django 5.0.2 on 2024-02-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0026_jobstatus2_studentid_alter_jobstatus2_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstatus2',
            old_name='StudentId',
            new_name='Studentid',
        ),
    ]
