# Generated by Django 5.0.2 on 2024-02-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0027_rename_studentid_jobstatus2_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus2',
            name='Studentid',
        ),
    ]
