# Generated by Django 5.0.2 on 2024-03-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0028_remove_jobstatus2_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus2',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.coursedb'),
        ),
    ]
