# Generated by Django 5.0.2 on 2024-03-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0030_jobstatus2_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus2',
            name='date_time',
        ),
    ]
