# Generated by Django 5.0.2 on 2024-03-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0032_trainingdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedb',
            name='DeptId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.departmentdb'),
        ),
    ]
