# Generated by Django 5.0.2 on 2024-04-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0033_alter_coursedb_deptid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='StudentId',
            new_name='Email',
        ),
    ]
