# Generated by Django 4.2.7 on 2024-04-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0034_rename_studentid_jobapplications_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyenrollmentdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
