# Generated by Django 4.2.7 on 2024-04-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0036_alter_facultyenrollmentdb_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyenrollmentdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
