# Generated by Django 4.2.7 on 2024-04-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0038_alter_facultyenrollmentdb_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyenrollmentdb',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
