# Generated by Django 4.2.7 on 2024-02-02 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminUI', '0014_studentdb_password'),
        ('Student', '0002_delete_answer_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected')], max_length=8)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.jobsdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
